### ISSUE TITLE
Rollbar won't compile for a Swift Mac OS app

### ISSUE THREAD

**Issue by ajram23** [rollbar/rollbar-apple#348]
**Describe the bug**
Trying to integrate with Rollbar in my swift APP

**To Reproduce**
1. Add swift package manager
2. Try to compile the app 
3. See error

**Expected behavior**
See attached screen shot

**Screenshots**
If applicable, ad
![Screenshot 2024-07-10 at 9 11 11 PM](https://github.com/rollbar/rollbar-apple/assets/125307567/cf32d719-68d5-4652-8536-de60fff259df)
![Screenshot 2024-07-10 at 9 11 05 PM](https://github.com/rollbar/rollbar-apple/assets/125307567/01d61463-cfb9-4a97-93c5-c3ffbfab59c1)
d screenshots to help explain your problem.

**Rollbar-Apple SDK version: v...**

**Calling the SDK from (x-mark all suitable):**
[] Objective-C
[X] Swift
[] Other: 

**Runtime environment (please complete the following information as applicable):**
 - Device: [e.g. macMini, iMac, iPhone, etc.] MacBook Pro
 - OS: [e.g. iOS, macOS, etc] MacOS
 - OS version: 15
 - Browser [e.g. chrome, safari] Not a browser
 - Browser version:
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by matux** [comment]
@ajram23 This should be fixed now in the latest 3.3.1. Cocoapods release may take a bit longer to go out. Thanks for the report!

**Comment by ajram23** [comment]
@matux Glad! Had to struggle with 2 weeks of back and forth with your support which ended up being a deadline. So grateful that you fixed this right away! Will check it out!

**Comment by matux** [comment]
Thank you for your patience, @ajram23. I'll make sure to pass your message.

**Comment by ajram23** [comment]
Can confirm this works! Thank you! 🙏🏼

**Comment by nemesis** [comment]
Hi there, I'm still getting an error:

```
.../checkouts/rollbar-apple/RollbarNotifier/Sources/RollbarCrash/Util/RollbarCrashMachineContext.c:42:9: error: missing '#include <sys/_types/_ucontext64.h>'; 'ucontext64_t' must be declared before it is used
```

Does this support a specific range of Xcode 16 betas? I'm trying it out on `Version 16.0 beta 5 (16A5221g)`

Thanks!

**Comment by nemesis** [comment]
Sorry, forgot to mention, I'm trying to run this as part of an iOS app. I can provide more debug info if needed?

**Comment by ajram23** [comment]
I am just another dev who filed the bug. Dont work for roller :)

**Comment by nemesis** [comment]
@matux I pushed a minimal repro project to https://github.com/nemesis/rollbar-xcode16

```bash
$ git clone
$ tuist install
$ tuist generate
```

seems that the issue is fixable by doing


```c
#include <sys/_types/_ucontext64.h>
```

before typedef'ing [here](https://github.com/rollbar/rollbar-apple/blob/c59d5a57a9661cf986d7e39b497dd925d87a018d/RollbarNotifier/Sources/RollbarCrash/Util/RollbarCrashMachineContext.c#L42)

**Comment by matux** [comment]
Thanks @nemesis @ajram23, this may have begun happening on the latest release of the Xcode 16 Beta (5).

I'm reopening this issue and working on fixing it, I believe there's a PR up already.

**Comment by nemesis** [comment]
Great, thanks for taking care of it!

**Comment by matux** [comment]
A new version 3.3.2 with the compilation issue addressed is out for SPM, Cocoapods release coming soon.

**Comment by timothyrobb** [comment]
Any update on that Cocoapods release after a month?

**Comment by matux** [comment]
@timothyrobb [3.3.2](https://cocoapods.org/pods/RollbarNotifier) is out now in Cocoapods, thank you for your patience!

**Comment by jostster** [comment]
Looks like this is still an issue @matux when building from commandline for localization. I am experiencing this on iOS and have RollbarSDK 3.3.2

**Comment by kevinconcourse** [comment]
@matux  How do i install this?

**Comment by diegoalex** [comment]
Same issue as @timothyrobb  here. App stop building after update to XCode 18.

I've checked the code here and the version 1.5.0 still pointing to the old RollbarNotifier version 

<img width="909" alt="image" src="https://github.com/user-attachments/assets/0b60c37b-10ce-41cd-9e86-36c022e3e4d7">
